### ISSUE TITLE
Adding a build tool

### ISSUE THREAD

**Issue by FanJups** [opensourcecameroon/jsGenerator#1]
Hi @opensourcecameroon ,

First of all, just want to congratulate you about this project, specially the creation of an open source community in Cameroon.

Why not add a build tool ? Maven ?

Well done 🙂 !

**Comment by sherlockwisdom** [comment]
Hello, thanks! :D Hoping to have more developers come around.

I'd confess my knowledge of Java isn't what it needs to be. I cannot use the tools it has available like Maven, and I only used Java for this project cus that's where JSOUP was.
I'd happily merge as many pull request as possible to add cool tools like this

**Comment by FanJups** [comment]
All right !
I'll try this week to add maven.
Secondly, why not turning this account type from personal to organisation ?

**Comment by FanJups** [comment]
It looks like there is already an organization : @opensource-cameroon . 

What's the difference between this user account and that organization account ?

**Comment by sherlockwisdom** [comment]
the twist is, opensourcecameroon (the user) is the owner of opensource-cameroon, the organization lol. It's been around for some years, but got inactive

**Comment by FanJups** [comment]
@Wisdom-Nji , sorry for the big delay.

This is the pull request : https://github.com/opensourcecameroon/jsGenerator/pull/2
